In [966]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot  as plt
from sklearn.linear_model import LinearRegression
from google.colab import drive
from sklearn.model_selection import train_test_split
import sklearn.preprocessing 

In [967]:
drive.mount('/content/gdriv')

Drive already mounted at /content/gdriv; to attempt to forcibly remount, call drive.mount("/content/gdriv", force_remount=True).


In [968]:
data_path = "/content/gdriv/My Drive/Colab Notebooks/data" 
print(data_path)

/content/gdriv/My Drive/Colab Notebooks/data


In [969]:
os.listdir(data_path)

['datasets_19_420_Iris.csv', 'archive.zip', 'car.csv', 'test_car.csv']

In [970]:
data_predict= pd.read_csv(data_path + '/test_car.csv')

In [971]:
data = pd.read_csv(data_path + '/car.csv')

In [972]:
data.head()

Year  Kilometers_Driven Fuel_Type  ... New_Price    Maker  Price
0  2015              41000    Diesel  ...       NaN  Hyundai  12.50
1  2011              46000    Petrol  ...      8.61    Honda   4.50
2  2012              87000    Diesel  ...       NaN   Maruti   6.00
3  2013              40670    Diesel  ...       NaN     Audi  17.74
4  2013              86999    Diesel  ...       NaN   Nissan   3.50

[5 rows x 11 columns]

In [973]:
col = data.columns
print(len(data))

5558


In [974]:
for col_value in col:
  detect_null = sum(data[col_value].isnull())
  print("{}에 포함된 결측값은 {}개 입니다".format(col_value, detect_null))

Year에 포함된 결측값은 0개 입니다
Kilometers_Driven에 포함된 결측값은 0개 입니다
Fuel_Type에 포함된 결측값은 0개 입니다
Owner_Type에 포함된 결측값은 0개 입니다
Mileage에 포함된 결측값은 0개 입니다
Engine에 포함된 결측값은 0개 입니다
Power에 포함된 결측값은 0개 입니다
Seats에 포함된 결측값은 2개 입니다
New_Price에 포함된 결측값은 4785개 입니다
Maker에 포함된 결측값은 0개 입니다
Price에 포함된 결측값은 0개 입니다


In [975]:
new_col = list(data.columns)

In [976]:
new_col

['Year',
 'Kilometers_Driven',
 'Fuel_Type',
 'Owner_Type',
 'Mileage',
 'Engine',
 'Power',
 'Seats',
 'New_Price',
 'Maker',
 'Price']

In [977]:
new_col.remove("New_Price")
new_col.remove('Seats')
new_col.remove('Maker')

In [978]:
print(new_col)

['Year', 'Kilometers_Driven', 'Fuel_Type', 'Owner_Type', 'Mileage', 'Engine', 'Power', 'Price']


In [979]:
data_new = data.loc[:,new_col]

In [980]:
data = data_new
data.head()

Year  Kilometers_Driven Fuel_Type Owner_Type  Mileage  Engine   Power  Price
0  2015              41000    Diesel      First    19.67    1582  126.20  12.50
1  2011              46000    Petrol      First    18.20    1199   88.70   4.50
2  2012              87000    Diesel      First    20.77    1248   88.76   6.00
3  2013              40670    Diesel     Second    15.20    1968  140.80  17.74
4  2013              86999    Diesel      First    23.08    1461   63.10   3.50

In [981]:
print(data.dtypes)

Year                   int64
Kilometers_Driven      int64
Fuel_Type             object
Owner_Type            object
Mileage              float64
Engine                 int64
Power                float64
Price                float64
dtype: object


In [982]:
data['Year'] = data['Year'].astype('object') 


In [983]:
data['Year'] = pd.Categorical(data['Year'])


In [984]:
data = pd.get_dummies(data,prefix_sep='_',drop_first=True)
data.head()

Kilometers_Driven  Mileage  ...  Owner_Type_Second  Owner_Type_Third
0              41000    19.67  ...                  0                 0
1              46000    18.20  ...                  0                 0
2              87000    20.77  ...                  0                 0
3              40670    15.20  ...                  1                 0
4              86999    23.08  ...                  0                 0

[5 rows x 30 columns]

In [985]:
train, test = train_test_split(data, train_size = 0.8)
train = train.reset_index(drop=True)
test = test.reset_index(drop=True)
print(len(train))
print(len(test))

4446
1112


In [986]:
col = list(train.columns)
print(col)
len(col)

['Kilometers_Driven', 'Mileage', 'Engine', 'Power', 'Price', 'Year_1999', 'Year_2000', 'Year_2001', 'Year_2002', 'Year_2003', 'Year_2004', 'Year_2005', 'Year_2006', 'Year_2007', 'Year_2008', 'Year_2009', 'Year_2010', 'Year_2011', 'Year_2012', 'Year_2013', 'Year_2014', 'Year_2015', 'Year_2016', 'Year_2017', 'Year_2018', 'Year_2019', 'Fuel_Type_Petrol', 'Owner_Type_Fourth & Above', 'Owner_Type_Second', 'Owner_Type_Third']


30

In [987]:
# Price 삭제 - 예측하는 값이기 때문
col.remove('Price')

In [988]:
trainY = train['Price'].to_numpy()
trainX = train.loc[:,col].to_numpy()

testY = test['Price'].to_numpy()
testX = test.loc[:,col].to_numpy()


In [989]:
testX

array([[1.2000e+05, 1.6200e+01, 1.4930e+03, ..., 0.0000e+00, 1.0000e+00,
        0.0000e+00],
       [1.3780e+05, 2.2300e+01, 1.2480e+03, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       [1.0000e+05, 1.7000e+01, 1.8960e+03, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       ...,
       [6.3777e+04, 1.8500e+01, 1.1970e+03, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       [9.4873e+04, 1.5300e+01, 1.5960e+03, ..., 0.0000e+00, 1.0000e+00,
        0.0000e+00],
       [3.6542e+04, 2.0000e+01, 1.3990e+03, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00]])

In [990]:
scaler = sklearn.preprocessing.MinMaxScaler()
trainX = scaler.fit_transform(trainX)
testX = scaler.fit_transform(testX)
print(trainX)

[[0.06560028 0.73661972 0.06959434 ... 0.         0.         0.        ]
 [0.02105497 0.7915493  0.25511723 ... 0.         0.         0.        ]
 [0.02637098 0.67852113 0.28265724 ... 0.         0.         0.        ]
 ...
 [0.03570078 0.         0.43970971 ... 0.         0.         0.        ]
 [0.0514036  0.71830986 0.10662449 ... 0.         0.         0.        ]
 [0.0681815  0.         0.5532192  ... 0.         0.         0.        ]]


In [991]:
model = LinearRegression(fit_intercept = False, normalize= True, copy_X=True)
print(model)

LinearRegression(copy_X=True, fit_intercept=False, n_jobs=None, normalize=True)


In [992]:
model.fit(trainX, trainY)

LinearRegression(copy_X=True, fit_intercept=False, n_jobs=None, normalize=True)

In [993]:
print('R-square: {}'.format(model.score(trainX, trainY)))
print('R-square: {}'.format(model.score(testX, testY)))


R-square: 0.697897397788248
R-square: 0.6901872585562163


In [994]:
model.coef_ # coef_ : 변수들에 대한 기울기


array([-17.71946486,  -6.01661505,  -6.17047141,  80.59167669,
         3.93529963,   5.36096954,   3.26200852,   5.47219316,
         2.64416718,   1.29641692,  -1.07614534,   0.85425749,
         1.83682799,  -0.37852453,  -0.26227562,   1.08259153,
         1.56466649,   2.99207622,   4.12533822,   4.99620477,
         6.62341909,   7.73862745,   9.11664793,  10.61237688,
        11.41933279,  -3.17007387,   1.9360164 ,  -0.09785039,
         0.35653931])

In [995]:
col_predict = data_predict.columns
print(len(data_predict))

250


In [996]:
for col_value in col_predict:
  detect_null = sum(data_predict[col_value].isnull())
  print("{}에 포함된 결측값은 {}개 입니다".format(col_value, detect_null))

Year에 포함된 결측값은 0개 입니다
Kilometers_Driven에 포함된 결측값은 0개 입니다
Fuel_Type에 포함된 결측값은 0개 입니다
Owner_Type에 포함된 결측값은 0개 입니다
Mileage에 포함된 결측값은 0개 입니다
Engine에 포함된 결측값은 0개 입니다
Power에 포함된 결측값은 0개 입니다
Seats에 포함된 결측값은 0개 입니다
New_Price에 포함된 결측값은 209개 입니다
Maker에 포함된 결측값은 0개 입니다


In [997]:
new_col_predict = list(data_predict.columns)

In [998]:
new_col_predict

['Year',
 'Kilometers_Driven',
 'Fuel_Type',
 'Owner_Type',
 'Mileage',
 'Engine',
 'Power',
 'Seats',
 'New_Price',
 'Maker']

In [999]:
new_col_predict.remove("New_Price")
new_col_predict.remove('Seats')
new_col_predict.remove('Maker')

In [1000]:
print(new_col_predict)

['Year', 'Kilometers_Driven', 'Fuel_Type', 'Owner_Type', 'Mileage', 'Engine', 'Power']


In [1001]:
data_new_predict = data_predict.loc[:,new_col_predict]

In [1002]:
data_predict = data_new_predict
data_predict.head()

Year  Kilometers_Driven Fuel_Type Owner_Type  Mileage  Engine   Power
0  2013              85000    Diesel      First    17.68    1968  174.33
1  2017              27000    Petrol      First    21.40    1197   83.10
2  2016              45794    Diesel      First    13.01    2199  194.30
3  2013              57352    Diesel      First    14.39    1998  163.70
4  2018              41467    Diesel      First    15.00    2143  204.00

In [1003]:
print(data_predict.dtypes)

Year                   int64
Kilometers_Driven      int64
Fuel_Type             object
Owner_Type            object
Mileage              float64
Engine                 int64
Power                float64
dtype: object


In [1004]:
data_predict['Year'] = data_predict['Year'].astype('object') 

In [1005]:
data_predict['Year'] = pd.Categorical(data_predict['Year'])

In [1006]:
data_predict = pd.get_dummies(data_predict,prefix_sep='_',drop_first=True)
data_predict.head()

Kilometers_Driven  Mileage  ...  Owner_Type_Second  Owner_Type_Third
0              85000    17.68  ...                  0                 0
1              27000    21.40  ...                  0                 0
2              45794    13.01  ...                  0                 0
3              57352    14.39  ...                  0                 0
4              41467    15.00  ...                  0                 0

[5 rows x 24 columns]

In [1007]:
col_2 = list(data_predict.columns)
print(col_2)
len(col_2)

['Kilometers_Driven', 'Mileage', 'Engine', 'Power', 'Year_2003', 'Year_2004', 'Year_2005', 'Year_2006', 'Year_2007', 'Year_2008', 'Year_2009', 'Year_2010', 'Year_2011', 'Year_2012', 'Year_2013', 'Year_2014', 'Year_2015', 'Year_2016', 'Year_2017', 'Year_2018', 'Year_2019', 'Fuel_Type_Petrol', 'Owner_Type_Second', 'Owner_Type_Third']


24

In [1008]:
len(col)

29

In [1009]:
col_3 = []
for i in col:
    if i not in col_2:
        col_3.append(i)

In [1010]:
print(col_2)
print(col)
col_3

['Kilometers_Driven', 'Mileage', 'Engine', 'Power', 'Year_2003', 'Year_2004', 'Year_2005', 'Year_2006', 'Year_2007', 'Year_2008', 'Year_2009', 'Year_2010', 'Year_2011', 'Year_2012', 'Year_2013', 'Year_2014', 'Year_2015', 'Year_2016', 'Year_2017', 'Year_2018', 'Year_2019', 'Fuel_Type_Petrol', 'Owner_Type_Second', 'Owner_Type_Third']
['Kilometers_Driven', 'Mileage', 'Engine', 'Power', 'Year_1999', 'Year_2000', 'Year_2001', 'Year_2002', 'Year_2003', 'Year_2004', 'Year_2005', 'Year_2006', 'Year_2007', 'Year_2008', 'Year_2009', 'Year_2010', 'Year_2011', 'Year_2012', 'Year_2013', 'Year_2014', 'Year_2015', 'Year_2016', 'Year_2017', 'Year_2018', 'Year_2019', 'Fuel_Type_Petrol', 'Owner_Type_Fourth & Above', 'Owner_Type_Second', 'Owner_Type_Third']


['Year_1999',
 'Year_2000',
 'Year_2001',
 'Year_2002',
 'Owner_Type_Fourth & Above']

In [1011]:
data_predict[col_3]=0

In [1012]:
scaler = sklearn.preprocessing.MinMaxScaler()
data_predict = scaler.fit_transform(data_predict)

In [1013]:
data_predict

array([[0.3373494 , 0.62253521, 0.26588022, ..., 0.        , 0.        ,
        0.        ],
       [0.10441767, 0.75352113, 0.09097096, ..., 0.        , 0.        ,
        0.        ],
       [0.17989558, 0.45809859, 0.31828494, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.14859438, 0.5665493 , 0.18194192, ..., 0.        , 0.        ,
        0.        ],
       [0.26746988, 0.81338028, 0.04582577, ..., 0.        , 0.        ,
        0.        ],
       [0.26425703, 0.53873239, 0.12363884, ..., 0.        , 0.        ,
        0.        ]])

In [1014]:
predict_price = model.predict(data_predict)
 

In [1015]:
predict_price

array([ 9.53577674e+00,  1.20225389e+01,  1.93233928e+01,  1.05202483e+01,
        2.27869668e+01,  3.41025190e+00, -1.78324927e+00,  1.96774233e+01,
        2.37859451e+00,  1.64747367e+01,  2.29302407e+00, -1.16762790e+00,
       -3.92468447e+00,  9.63357919e+00,  1.39305070e+01,  1.08186827e+01,
        1.75175988e+00,  2.35756936e+01,  1.37326156e+01,  1.52597996e+01,
        1.31361253e+01,  7.75427162e+00,  4.30259015e+00,  5.98521438e+00,
        1.05025531e+01,  1.45870550e+01,  8.76619822e+00,  4.96336925e-01,
        1.39141772e+01,  1.17730795e+01,  9.38879862e+00,  3.34128950e+01,
        1.42037128e+01,  9.21889137e+00, -5.80195844e-01,  9.80020202e+00,
        8.45320639e+00,  9.28617869e+01,  2.70466221e+01,  1.73393831e+01,
        2.18934032e+00, -4.34944582e-02,  7.49691279e+00,  3.10507189e+00,
        1.19973168e+01,  1.10492318e+01, -1.13466976e+00,  2.12339411e+01,
        9.30467714e+00,  5.18599326e+00,  5.13231436e+00,  1.03704753e+01,
        1.03192338e+01,  

In [1016]:
df = pd.DataFrame(predict_price)

In [1017]:
df.to_csv('C:\\Users\\Mgyu\\homework_5_202027518.csv')